# action.yml
name: 'Terraform Workspace setup'
description: 'Setup a Terraform Cloud/Enterprise workspace'
inputs:
  organization:
    description: 'Terraform Organization name'
    required: true
  workspace:
    description: 'Terraform Workspace name'
    required: true
  token:
    description: 'Terraform API token'
    required: true
  vars:
    description: 'Variables to create in workspace'
    required: false
    default: '{"vars": []}'
outputs:
  workspace_id:
    description: 'The created or updated Terraform workspace ID'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.organization }}
    - ${{ inputs.workspace }}
    - ${{ inputs.token }}
    - ${{ inputs.vars }}