on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world action step
        id: hello
        uses: ./
        with:
          organization: "terraform-deepdive"
          workspace: "sample-actions1"
          token: ${{ secrets.TF_API_TOKEN }}

      - name: Get the output time
        run: echo "The workspace ID is ${{ steps.hello.outputs.workspace_id }}"